version: '3.8'

services:
  db:
    image: mariadb:latest
    restart: always
    env_file:
      - .env
    environment:
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      MARIADB_DATABASE: ${MARIADB_DATABASE}
      MARIADB_USER: ${MARIADB_USER}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD}
    ports:
      - "3308:3306"
    volumes:
      - db_data:/var/lib/mysql

  backend:
    build: ./backend
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      DB_HOST: db
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      DB_NAME: ${DB_NAME}
      DB_PORT: ${DB_PORT}
      JWT_SECRET: ${JWT_SECRET}
      PORT: ${PORT}
    depends_on:
      - db

  vrisa:
    build: ./vrisa
    ports:
      - "8082:80"
    depends_on:
      - backend

  rip-server:
    build: ./rip-js-server
    ports:
      - "2055:2055"

volumes:
  db_data:
